### ISSUE TITLE
Create Wireframe and Initial HTML  

### ISSUE THREAD

**Issue by treecao** [treecao/lyric-translator#2]
@Tieranyr please attach your Wireframe here to this issue 

Initial Concept Brainstorming:

- [x] How many screens will we display? (2)

1. landing page with search capabilities
2. populate song lyrics with translation 

- [x] How will HTML be formated? 
- [x] Who will create HTML (Tierany)

**Comment by Tieranyr** [comment]
![Image](https://user-images.githubusercontent.com/91648328/214195048-368619ff-e266-4ce8-b271-ea261e3910b9.png)
