### ISSUE TITLE
Powerpoint Presentation 

### ISSUE THREAD

**Issue by treecao** [treecao/lyric-translator#21]
https://docs.google.com/presentation/d/10QaO9KH8HtUXj__81ve0SZcpO5DbMbqqQr4iPpbwKks/edit#slide=id.g29f43f0a72_0_24

**Comment by Tieranyr** [comment]
Let us know of any additions [https://prezi.com/view/uyd7TaLyvGtc2zOAcpGO/](url)

**Comment by Tieranyr** [comment]
Let us know if any additions [https://prezi.com/view/uyd7TaLyvGtc2zOAcpGO/](url)

**Comment by Tieranyr** [comment]
Let me and @AhtziryCavazos know of any additions. https://prezi.com/view/uyd7TaLyvGtc2zOAcpGO/  @treecao

**Comment by treecao** [comment]
It's looking good so far. good job with the formatting @Tieranyr 
I'm dropping notes into our group doc for the presentation/set up to have a clean look at raw data. 
https://docs.google.com/document/d/1ALB_scpzs-q9ma3BZGYwlgqp9axqMiV5hUKXOI1sLU4/edit#
